name: NSLookup Tool (ubuntu-latest)
on:
  workflow_dispatch:
    inputs:
      host:
        description: 'Hostname'
        default: 'github.com'
        required: true
        type: string
jobs:
  nslookup:
    runs-on: ubuntu-latest
    steps:
    - name: Run NSLookup...
      run: nslookup ${{ github.event.inputs.host }}
